spring.application.name=project

#1 - Usuário do banco
spring.datasource.username = root

#2 - Senha do banco
spring.datasource.password = mysql123

#3 - URL para a base de dados
spring.datasource.url = jdbc:mysql://localhost:3306/users?useTimezone=true&serverTimezone=UTC

#4 - Controla o que o Hibernate faz com o schema do banco quando a aplicação sobe (nunca use 'update' em produção).
# O 'create' apaga tudo e cria de novo toda vez que sobe a aplicação.
spring.jpa.hibernate.ddl-auto=update

#5 - Isso faz o Hibernate imprimir as queries no console.
spring.jpa.properties.hibernate.format_sql=false

#6 - Ativa o pretty print do browser.
spring.jackson.serialization.indent-output=true
